### ISSUE TITLE
Can't unmute audio from keyboard

### ISSUE THREAD

**Issue by surtarso** [CyphrRiot/ArchRiot#26]
Yellow,

The mute key (physical) mutes audio but does not unmute it. Lowering or raising the volume does not unmute as well, so the only option is grabbing the mouse and clicking the volume applet on the waybar.

Cheers

**Comment by CyphrRiot** [comment]
I believe I fixed it. You should be able to run `curl -fsSL https://ArchRiot.org/setup.sh | bash` OR pull the latest git repo for the Volume.sh and hyprland.conf updates.

**Comment by surtarso** [comment]
## I modified the packages.yaml (so mullpnv wont get re-installed for ex), should I run the curl script or execute the local setup.sh? (Sorry, still not perfectly clear for me)

I've been backing up anything I touch just in case, here is the list of files I modified:
```
confs/
├── aliases.fish -> ../.config/fish/conf.d/local.fish
├── default_packages.yaml -> ../.local/share/archriot/install/packages.yaml
├── hyprland.conf -> ../.config/hypr/hyprland.conf
├── keybindings -> ../.config/hypr/keybindings.conf
├── lockscreen -> ../.config/hypr/hyprlock.conf
├── minimize-toggle.sh -> ../.local/share/archriot/config/bin/minimize-toggle.sh
├── monitors -> ../.config/hypr/monitors.conf
├── ssh-agent.fish -> ../.config/fish/conf.d/ssh-agent.fish
├── wallpaper_switch -> ../.local/share/archriot/config/bin/swaybg-next
├── waybar_config -> ../.config/waybar/config
└── waybar_modules -> ../.config/waybar/Modules
```

extra packges installed so far are only: (should I add those to my personal packages.yaml?)
```
λ ~ ➤ history | grep -i "-S" 
sudo pacman -S gimp
sudo pacman -S cava
sudo pacman -S nfs-utils
sudo pacman -S nfs-server
yay -S autofs
sudo pacman -S openssh
sudo pacman -S code
sudo pacman -S krita
```

and removed: (I also removed those on packaged.yaml)
```
λ ~ ➤ history | grep -i "-R" 
sudo pacman -R iwd
sudo pacman -R signal-desktop
sudo pacman -R mullvad-vpn-bin
sudo pacman -R cups cups-pdf cups-filters system-config-printer
sudo pacman -R blueberry
```

I will just grab those 2 files individually for now.

**Comment by surtarso** [comment]
Thanks, that fixed it =)
